site_name: Céu-SDL v0.20 - Reference Manual
theme:     readthedocs
#site_dir:  site/v0.20

pages:
- Home:                 index.md
- Introduction:         010-introduction.md
- Modes of Operation:   020-modes.md
- Input Events:         030-inputs.md
- License:              license.md

